version: '3.8'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    networks:
      - backend
  
  example-api:
    depends_on:
      - postgres
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - DB_MIGRATE=no
      - DB_HOST=postgres
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DATABASE
      - DB_PORT=$POSTGRES_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend

volumes: 
  db:

networks:
  backend:
